const fs = require('fs');
let content = fs.readFileSync('src/pages/DashboardPage.tsx', 'utf-8');

content = content.replace(
  '<header className=\"glass p-4 md:p-6 flex justify-between items-center gap-4 rounded-xl shadow-sm mb-6 border border-white/20 dark:border-white/5\">',
  '<header className=\"glass p-4 md:px-6 md:py-4 flex flex-col md:flex-row md:justify-between md:items-center gap-4 rounded-xl shadow-sm mb-6 border border-white/20 dark:border-white/5\">'
);
content = content.replace(
  '<div className=\"flex gap-8 border-t border-slate-200 dark:border-white/5 pt-4\">',
  '<div className=\"flex flex-col sm:flex-row gap-4 sm:gap-8 border-t border-slate-200 dark:border-white/5 pt-4\">'
);
content = content.replace(
  '<div className=\"flex items-center gap-2\">',
  '<div className=\"flex items-center gap-2 flex-wrap mt-2 md:mt-0 w-full md:w-auto\">'
);
content = content.replace(
  '<div className=\"flex items-center gap-2\">',
  '<div className=\"flex items-center gap-2 flex-wrap w-full md:w-auto\">'
);
content = content.replace(
  '<div className=\"grid grid-cols-4 gap-4 mb-6\">',
  '<div className=\"grid grid-cols-2 md:grid-cols-4 gap-4 mb-6\">'
);
content = content.replace(
  '<div className=\"flex gap-6\">',
  '<div className=\"flex gap-6 sm:gap-8\">'
);
content = content.replace(
  '<div className=\"flex gap-8\">',
  '<div className=\"flex gap-6 sm:gap-8\">'
);

// Also need the mobile horizontal scrolling for KPI categories
// Wait, the KPI categories list is generated by `activeCategories.map(...)` 
// and wrapped in a div. Let's find it.
const kpiCatTarget = `<div className=\"flex gap-3 overflow-x-auto pb-2 hide-scrollbar\">
            {Object.entries(kpiMetrics).map(([category, m]) => (`;
const kpiCatReplace = `<div className=\"md:hidden flex gap-3 overflow-x-auto pb-2 hide-scrollbar w-full\">
            {Object.entries(kpiMetrics).map(([category, m]) => (`;
content = content.replace(kpiCatTarget, kpiCatReplace);

fs.writeFileSync('src/pages/DashboardPage.tsx', content);
console.log('Fixed responsiveness.');
